@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.jozufozu.exnihiloomnia.client;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;