@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.jozufozu.exnihiloomnia.common.registries;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;