@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.jozufozu.exnihiloomnia.advancements;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;