@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.jozufozu.exnihiloomnia.common.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;