@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.jozufozu.exnihiloomnia.common.blocks.crucible;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;