@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.jozufozu.exnihiloomnia.advancements.triggers;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;